#! /bin/bash

WORK_DIR=/tmp/
DEVICE=/dev/sdd


if [ $# -eq 2 ] 
then
  WORK_DIR=$1
  DEVICE=$2
else
  echo "Usage: $0 $WORK_DIR $DEVICE"
  echo "    dir to storage: $DISK_IMAGE"
  echo "    device to copy: $DEVICE"
  exit -1
fi

mkdir -p $WORK_DIR
cd $WORK_DIR

r66-get-rfs-tarball $DEVICE
# Resultado: sdd1.tar.gz sdd2.tar.gz sdd3.tar.gz
md5sum $WORK_DIR/sdd1.tar.gz > $WORK_DIR/sdd1.tar.gz.md5sum
md5sum $WORK_DIR/sdd2.tar.gz > $WORK_DIR/sdd2.tar.gz.md5sum
md5sum $WORK_DIR/sdd3.tar.gz > $WORK_DIR/sdd3.tar.gz.md5sum

r66-generate-iso-image $WORK_DIR $WORK_DIR/sdd.img

r66-get-partition-from-iso-image $WORK_DIR/sdd.img 1 $WORK_DIR/sdd1.img
gzip -c $WORK_DIR/sdd1.img > $WORK_DIR/sdd1.img.gz
md5sum $WORK_DIR/sdd1.img.gz > $WORK_DIR/sdd1.img.gz.md5sum
rm $WORK_DIR/sdd1.img

r66-get-partition-from-iso-image $WORK_DIR/sdd.img 2 $WORK_DIR/sdd2.img
gzip -c $WORK_DIR/sdd2.img > $WORK_DIR/sdd2.img.gz
md5sum $WORK_DIR/sdd2.img.gz > $WORK_DIR/sdd2.img.gz.md5sum
rm $WORK_DIR/sdd2.img

r66-get-partition-from-iso-image $WORK_DIR/sdd.img 3 $WORK_DIR/sdd3.img
gzip -c $WORK_DIR/sdd3.img > $WORK_DIR/sdd3.img.gz
md5sum $WORK_DIR/sdd3.img.gz > $WORK_DIR/sdd3.img.gz.md5sum
rm $WORK_DIR/sdd3.img

gzip -c $WORK_DIR/sdd.img > $WORK_DIR/sdd.img.gz
md5sum $WORK_DIR/sdd.img.gz > $WORK_DIR/sdd.img.gz.md5sum
rm $WORK_DIR/sdd.img
